export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const ADD_TASKS_SUCCESS = "ADD_TASKS_SUCCESS";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const REMOVE_TASK =  "REMOVE_TASK";
export const REMOVE_SELECTED_TASKS = "REMOVE_SELECTED_TASKS";
export const EDIT_TASKS_SUCCESS = "EDIT_TASKS_SUCCESS";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const REMOVE_SINGLE_TASK =  "REMOVE_SINGLE_TASK";
export const CHANGE_TASK_STATUS =  "CHANGE_TASK_STATUS";